version: "3.7"
services:
  personal-frontend:
    build: .
    ports:
      - "3003:3003"

    networks:
      - deployment-server_jakubsekula-network

networks:
  deployment-server_jakubsekula-network:
    external: true