version: "3.7"
services:
  personal-backend:
    build: ./backend
    volumes:
      - "./volumes/backend/database/data.db:/home/app/database/data.db"
      - "./volumes/backend/public/uploads/:/home/app/public/uploads/"
    ports:
      - "8081:8081"
    networks:
      - deployment-server_jakubsekula-network

  personal-frontend:
    depends_on:
      - personal-backend
    build: ./frontend
    ports:
      - "8080:8080"

    networks:
      - deployment-server_jakubsekula-network

networks:
  deployment-server_jakubsekula-network:
    external: true