version: "3.7"
services:
  personal-backend:
    build: .
    volumes:
      - "../volumes/backend/database/data.db:/home/app/database/data.db"
      - "../volumes/backend/public/uploads/:/home/app/public/uploads/"
    ports:
      - "3002:3002"
    networks:
      - deployment-server_jakubsekula-network

networks:
  deployment-server_jakubsekula-network:
    external: true