import Head from 'next/head'
import { useEffect, useState } from 'react'
import { IconMoon, IconSun } from "@tabler/icons";
import PaperComponent from '@/components/PaperComponent';
import { useMantineColorScheme } from '@mantine/core';
import { ColorSchemeToggle } from '@/components/ColorSchemeToggle';

export default function Home() {
  const [mounted,setMounted] = useState(false)
  const { colorScheme, toggleColorScheme } = useMantineColorScheme();

  useEffect(()=>{
    setMounted(true)
  },[])

  const renderThemeChanger = () => {
    if (!mounted) return null;

    if (colorScheme === "dark") {
      return (
        <IconSun
          className="w-7 h-7"
          onClick={() => {
            toggleColorScheme();
          }}
        />
      );
    } else {
      return (
        <IconMoon
          className="w-7 h-7"
          onClick={() => {
            toggleColorScheme();
          }}
        />
      );
    }
  };


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='max-w-[1400px] mx-auto'>
        <ColorSchemeToggle />
        <h1>Test app</h1>
        <PaperComponent className="w-1/3 mb-2" />
        <PaperComponent className="w-1/3" />
      </main>
    </>
  )
}
